geyserfund/geyser-app

- src/constants/components/id.ts
- src/pages/projectView/projectCreatorViews/sections/overview/ProjectCreatorOverview.tsx
- src/pages/projectView/projectCreatorViews/sections/overview/components/ContributorsComponent.tsx
- src/translations/English.json
> fix: add paginated contributions for the week data in contribution

- src/context/project.tsx
adds sentry exceptions before project not found error screen
> fix: add sentry capture exception for project not found error

- src/components/molecules/AppFooter.tsx
- src/config/routes/routes.tsx
- src/constants/config/routerPaths.ts
- src/constants/platform/url.ts
- src/pages/landing/filters/FilterFooter.tsx
- src/pages/legal/PrivacyPolicy.tsx
- src/pages/legal/TermsAndConditions.tsx
- src/pages/legal/index.ts
- src/pages/projectCreate/components/ProjectCreateCompleted.tsx
Issue: GEY-5430
https://linear.app/geyser/issue/GEY-5430/terms-and-condition-page
> Moving terms and conditions away from Notion

- src/graphql/fragments/funding.ts
- src/graphql/fragments/project.ts
- src/hooks/fundingFlow/useFundingFlow.tsx
- src/pages/projectView/projectActivityPanel/screens/success/SuccessScreen.tsx
- src/pages/projectView/projectActivityPanel/screens/success/components/ContributionShippingBox.tsx
- src/pages/projectView/projectMainBody/components/MilestoneAdditionModal.tsx
- src/types/generated/graphql.ts
resolves GEY-5453
Includes,
- addition of a query even if the success was received from subscription.
> fix: add creator email to shipping info

- src/pages/projectView/projectMainBody/components/MilestoneAdditionModal.tsx
- src/translations/English.json
> fix: milestones copy update and add transaltions

- src/pages/projectCreate/ProjectCreationWalletConnectionForm.tsx
1. resolves issue where user is unable to edit wallet.
> fix: update wallet enable

- src/pages/projectCreate/ProjectCreationWalletConnectionForm.tsx
hot fix for project not being able to finalize due to error in wallet update
> fix: hotfix  consider empty  case

- src/pages/projectView/projectMainBody/components/MilestoneAdditionModal.tsx
> fix: milestone addition bug

- src/components/molecules/ImageCropperModal.tsx
- src/constants/platform/url.ts
- src/pages/projectView/projectCreatorViews/sections/contributors/components/EmptyContainer.tsx
- src/pages/projectView/projectCreatorViews/sections/contributors/sections/paymentsAndAccounting/PaymentsAndAccoutningList.tsx
- src/pages/projectView/projectCreatorViews/sections/contributors/sections/pendingPayments/PendingPaymentsList.tsx
- src/pages/projectView/projectCreatorViews/sections/contributors/sections/rewards/Rewards.tsx
> fix: remove skip crop button, and change images

- src/constants/platform/defaultViewTags.ts
> changeset: update featured project to bitcoinstickerbonanza2

- src/pages/projectCreate/ProjectCreate.tsx
- src/pages/projectCreate/ProjectCreateCompletion.tsx
> fix: project launch button was clickable

- src/pages/projectCreate/ProjectCreationWalletConnectionForm.tsx
- src/pages/projectCreate/hooks/useWalletForm.tsx
> fix: update styling for lightning error

- src/pages/projectCreate/ProjectCreationWalletConnectionForm.tsx
> fix: put alby on the end of example wallets

- src/defaults/projectReward.ts
- src/graphql/fragments/funding.ts
- src/pages/projectView/projectCreatorViews/sections/insights/components/InsightsStatsComponent.tsx
- src/pages/projectView/projectCreatorViews/sections/overview/components/ContributorsComponent.tsx
- src/pages/projectView/projectCreatorViews/sections/rewards/subviews/Shared/ProjectRewardForm.tsx
- src/pages/projectView/projectMainBody/components/ProjectRewardPanel.tsx
- src/types/generated/graphql.ts
Resolves 6226, 6214, 6186, 6164, 6085
> feat: high priority bugs

- src/hooks/useUserLightningAddress.tsx
- src/pages/auth/ConnectAccounts.tsx
- src/pages/auth/ConnectWithSocial.tsx
- src/pages/profile/Profile.tsx
- src/pages/profile/hooks/useEditProfileModal.ts
- src/pages/profile/type.ts
- src/pages/profile/views/account/AccountInfo.tsx
- src/pages/profile/views/account/EditProfileModal.tsx
- src/pages/profile/views/account/Summary.tsx
- src/pages/profile/views/badges/Badges.tsx
- src/pages/profile/views/badges/BadgesBody.tsx
- src/pages/profile/views/profileTabs/ProfileActivity.tsx
- src/pages/profile/views/profileTabs/ProfileContributions.tsx
- src/pages/profile/views/profileTabs/ProfileFollowed.tsx
- src/pages/profile/views/profileTabs/ProfileProjects.tsx
- src/pages/profile/views/profileTabs/ProfileTabs.tsx
- src/utils/validations/hasExternalAccount.ts
- src/utils/validations/wallet.ts
> fix: refresh user on add account, and change type

- src/pages/projectView/projectCreatorViews/sections/contributors/components/OrderItems.tsx
- src/pages/projectView/projectCreatorViews/sections/contributors/sections/rewards/components/RewardTable.tsx
> feat: move reward items to table and reference code to inside accordion

- src/components/layouts/LandingCardBase.tsx
- src/hooks/graphqlState/useFollowProject.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/components/ContributionSummary.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/components/ProfileOrderCard.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/components/ProfileProjectCard.tsx
- src/pages/landing/components/FundingStatWithFollow.tsx
- src/pages/landing/components/LandingEntryCard.tsx
- src/pages/landing/components/LandingProjectCard.tsx
- src/pages/landing/projects/elements/FeaturedProjectCard.tsx
- src/pages/projectView/projectActivityPanel/screens/info/ActivityBrief.tsx
- src/pages/projectView/projectMainBody/components/FollowButton.tsx
- src/pages/projectView/projectMainBody/sections/Header.tsx
partially resolves GYS-6304, GYS-6308, GYS-6336
> staging-fixes

- src/modules/profile/pages/profilePage/views/profileTabs/components/ContributionSummary.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/components/TabComponent.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/hooks/useProfileOrders.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/views/ProfileProjects.tsx
- src/translations/English.json
> fix: final touchups

- src/navigation/topNavBar/TopNavBar.tsx
- src/pages/entry/EntryDetails.tsx
- src/pages/entry/creation/EntryPreview.tsx
- src/pages/landing/feed/components/EntryActivityItem.tsx
- src/pages/projectCreate/ProjectCreateCompletion.tsx
- src/pages/projectCreate/hooks/useProjectForm.tsx
- src/pages/projectCreate/hooks/useProjectStoryForm.tsx
- src/pages/projectCreate/hooks/useWalletForm.tsx
- src/pages/projectDashboard/ProjectDashboard.tsx
- src/pages/projectDashboard/navigation/BackToProjectMobile.tsx
- src/pages/projectDashboard/sections/ProjectNostrSettings.tsx
- src/pages/projectView/projectActivityPanel/screens/success/SuccessScreen.tsx
- src/pages/projectView/projectCreatorViews/sections/overview/components/ContributorsComponent.tsx
- src/pages/projectView/projectCreatorViews/sections/overview/components/OverviewHeader.tsx
- src/pages/projectView/projectCreatorViews/sections/rewards/subviews/Shared/ProjectRewardForm.tsx
- src/pages/projectView/projectMainBody/components/MilestoneAdditionModal.tsx
- src/pages/projectView/projectMainBody/sections/Entries.tsx
- src/pages/projectView/projectMainBody/sections/Header.tsx
- src/pages/projectView/projectMainBody/sections/Milestones.tsx
- src/pages/projectView/projectNavigation/components/ProjectCreatorModal.tsx
- src/types/generated/graphql.ts
- src/utils/validations/wallet.ts
- Adds null/undefined checks to avois type issues , that were created for the generated types after constraint changes
> fix: add null/undefined checks to resolves type issues

- src/pages/projectView/projectMainBody/sections/Header.tsx
https://github.com/geyserfund/geyser-app/issues/1214
> feat: added thumbnail popup

- src/config/apollo-client/apolloClient.ts
> fix: retry when status code is 408

- src/modules/profile/pages/profilePage/views/account/components/ConnectAccounts.tsx
> fix: remove connect accounts on other profile

- src/components/molecules/projectDisplay/ProjectRewardAvailability.tsx
- src/components/molecules/projectDisplay/ProjectRewardShippingEstimate.tsx
- src/components/molecules/projectDisplay/RewardCard.tsx
- src/config/theme/theme.ts
- src/pages/projectView/projectMainBody/components/ProjectRewardPanel.tsx
- src/pages/projectView/projectMainBody/sections/Rewards.tsx
- src/styles/colors.ts
> fix: update reward card design uptodate with figma

- src/modules/profile/pages/profileSettings/components/ProfileForm.tsx
> fix: move email and delete profile outside of profile settings form

- src/constants/platform/subscription.ts
- src/pages/landing/projects/components/SubscribeToProjects.tsx
> changeset: add 3 more projects that display the subscribe button

- src/pages/projectCreate/ProjectCreateCompletion.tsx
- src/pages/projectCreate/ProjectCreationWalletConnectionPage.tsx
> fix: create wallet on project wallet add page

- src/config/apollo-client/apolloClient.ts
> fix: increase retry number to 4

- src/context/project.tsx
- src/pages/projectCreate/components/ProjectCreateLaunchedModal.tsx
- src/translations/English.json
> Fix-final-fixes

- src/constants/platform/url.ts
https://linear.app/geyser/issue/GYS-6834/update-faq-link
> feat: update FAQ url

- src/pages/entry/creation/EntryPreview.tsx
> fix: routing for goToEntry

- src/pages/projectCreate/ProjectCreateStart.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-6866/change-copy-in-creation-flow
> fix: change copy in creation flow

- src/constants/platform/url.ts
- src/pages/projectDashboard/sections/ProjectWallet.tsx
https://linear.app/geyser/issue/GYS-6865/connect-wallet-issue
> fix: email verification on wallet connect text

- src/pages/projectView/projectMainBody/components/ContributeButton.tsx
https://linear.app/geyser/issue/GYS-6819/when-i-click-contribute-the-project-page-doesnt-change-to-rewards
> fix: when user clicks contribute - rewards are displayed

- src/pages/projectCreate/ProjectCreationWalletConnectionForm.tsx
- src/pages/projectDashboard/sections/ProjectWallet.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-6525/frontend-monetization-component-updates
> fix: minor post QA fix

- src/pages/projectView/ProjectContainer.tsx
> Hotfix: no seo image for project url

- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/views/ActivityBrief.tsx
https://linear.app/geyser/issue/GYS-6659/full-list-of-contributors-is-not-showing
> fix: change filter criteria for funders

- src/modules/project/pages/projectView/components/ProjectCreateDraftModal.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-6909/copy-update-explaining-draft-projects
> fix: change copy after putting project in draft

- src/modules/project/pages/projectView/views/projectMainBody/sections/ShareProject.tsx
- src/modules/project/pages/projectView/views/projectMainBody/utils.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-6744/update-share-project-to-include-share-to-twitter
> feat: share to twitter button

- src/modules/project/pages/projectView/views/projectMainBody/components/ProjectRewardPanel.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/RewardCard.tsx
https://linear.app/geyser/issue/GYS-7087/you-can-buy-rewards-of-inactive-projects
> feat: disable reward selection when project is inactive

- src/pages/fallback/NotFoundPage.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-7022/edit-copy-in-404-error
> fix: more precise error message on not found page

- src/constants/platform/geyserFee.ts
- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/views/ActivityBrief.tsx
- src/utils/helpers/projectHelpers.ts
> fix: remove fee reduction for display

- src/components/icons/svg/InReviewIcon.tsx
- src/components/ui/ProjectStatusLabel.tsx
- src/types/generated/graphql.ts
- src/utils/validations/project.ts
https://linear.app/geyser/issue/GYS-7009/frontend-implement-in-review-logic
> feat: add in review status

- src/modules/project/pages/projectCreate/views/ProjectCreateStart.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-7137/change-copy-on-project-creation-when-not-logged-in
> fix: edit copy on project creation

- src/components/icons/svg/InReviewIcon.tsx
- src/modules/project/components/ProjectFeeSelection.tsx
- src/modules/project/forms/ProjectCreationWalletConnectionForm.tsx
- src/modules/project/pages/projectCreate/components/ProjectCreationCreateReward.tsx
- src/modules/project/pages/projectCreate/components/ProjectCreationEditReward.tsx
- src/pages/fallback/NotFoundPage.tsx
https://linear.app/geyser/issue/GYS-7138/qa-issues-240417
> Fix: Post QA fixes

- src/pages/landing/projects/views/DefaultView.tsx
> hotfix: remove subscribe section and add featured grant

- .eslintrc.cjs
- src/pages/grants/constants.ts
> fix: add grant round 6 to the list

- src/config/routes/routes.tsx
- src/constants/config/routerPaths.ts
- src/modules/project/pages/projectCreate/views/ProjectCreateCompletionPage.tsx
- src/modules/project/pages/projectView/ProjectContainer.tsx
- src/modules/project/pages/projectView/views/projectMainBody/ProjectMainBody.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/ContributeButton.tsx
update project draft url for seo
> fix: redirect to draft url for projects in draft

- src/components/ui/LinkableAvatar.tsx
https://linear.app/geyser/issue/GYS-7099/we-can-show-more-of-the-username
> fix: longer username

- src/graphql/queries/grant.ts
- src/pages/grants/grantsPage/GrantPage.tsx
- src/pages/grants/grantsPage/GrantsRoundOne.tsx
- src/pages/grants/grantsPage/GrantsRoundTwo.tsx
- src/pages/grants/grantsPage/sections/CommunityVoting.tsx
- src/pages/grants/grantsPage/sections/DistributionChart.tsx
- src/types/generated/graphql.ts
https://linear.app/geyser/issue/GYS-7399/update-community-voting-grant
> Grant for Bitcoin Prague

- src/pages/grants/constants.ts
- src/pages/grants/hooks/useGrant.tsx
- src/pages/grants/hooks/useGrants.tsx
- src/pages/landing/projects/elements/FeaturedGrantCard.tsx
- src/pages/landing/projects/views/DefaultView.tsx
> fix: add new url params and grant-round-08

- src/pages/grants/constants.ts
- src/pages/grants/grantsPage/GrantPage.tsx
- src/pages/grants/grantsPage/sections/GrantSummary.tsx
> fix: grants update request

- src/modules/project/context/FundingProvider.tsx
- src/modules/project/funding/hooks/useFundingFlow.ts
https://linear.app/geyser/issue/GYS-7739/grants-issue-internal-bug
> fix: grants issue - project provider - funding flow bug

- src/pages/fallback/NotFoundProject.tsx
https://linear.app/geyser/issue/GYS-7412/project-not-found-on-mobile-bug
> fix: not found project mobile fixed

- src/pages/grants/grantsPage/GrantPage.tsx
> fix: not be showing 'let the sats flow' in the bitcoin beach grant

- src/App.tsx
- src/config/matomo.ts
> fix: initial matomo configuration

- src/components/inputs/ControlledGoalAmount.tsx
- src/components/molecules/projectActivity/SatsAmount.tsx
- src/components/ui/SatoshiAmount.tsx
- src/components/ui/Tooltip.tsx
- src/modules/profile/pages/profilePage/views/summary/SummaryBody.tsx
- src/modules/project/pages/projectView/hooks/useProjectGoalForm.tsx
- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/components/ProjectBalanceDisplay.tsx
- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/hooks/useProjectDefaultGoal.tsx
- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/views/ActivityBrief.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/GoalCompleted.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/GoalInProgress.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/CreatorTools.tsx
- src/utils/formatData/helperFunctions.ts
https://linear.app/geyser/issue/GYS-7806/goal-fixes
> Goal fixes

- src/modules/project/pages/projectView/views/projectActivityPanel/ProjectActivityPanel.tsx
https://linear.app/geyser/issue/GYS-7845/real-time-progress-update-for-the-contributor
> Update goals after contributions

- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/components/ProjectBalanceDisplay.tsx
> fix: show only goal if balance is 0

- src/modules/project/pages/projectCreate/components/ProjectCreationRewards.tsx
- src/modules/project/pages/projectView/views/projectCreatorViews/sections/rewards/components/RewardsTable.tsx
https://linear.app/geyser/issue/GYS-7631/rewards-sort-by-creation-date
> Rewards always sorted by cost

- src/modules/project/pages/projectView/views/projectMainBody/sections/Header.tsx
https://linear.app/geyser/issue/GYS-7835/make-contributors-text-clickable
> feat: go to leaderboard on contributors click

- src/modules/project/pages/projectView/hooks/useProjectShare.ts
- src/modules/project/pages/projectView/views/projectActivityPanel/screens/contributionInfo/components/CopyProjectLink.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/ShareButton.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/ShareProject.tsx
- src/navigation/topNavBar/components/ProjectTitle.tsx
> feat: add mtm codes to share project sections

- src/graphql/queries/grant.ts
- src/graphql/queries/project.ts
- src/hooks/graphqlState/useEntryState.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/BeachGrantEntryTemplate.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/CreatorTools.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/Entries.tsx
- src/pages/entry/creation/editor/EntryCreateEdit.tsx
- src/translations/English.json
- src/types/generated/graphql.ts
> feat: add entry template for bitcoin beach grant applicants

- src/config/matomo.ts
add subdomain support for matomo
> hotfix: add matomo subdomain support

- src/config/matomo.ts
Reverts geyserfund/geyser-app#1513
> Revert "hotfix: add matomo subdomain support"

- src/pages/entry/creation/EntryPreview.tsx
- src/pages/entry/creation/editor/CreateNav.tsx
add publish button to top navbar
> feat: add entry publish button top navbar

- src/modules/project/pages/projectView/views/projectActivityPanel/screens/info/hooks/useProjectDefaultGoal.tsx
- src/modules/project/pages/projectView/views/projectMainBody/components/GoalModal.tsx
https://linear.app/geyser/issue/GYS-7940/goal-nice-to-have-small-fixes
> Goals nice to have small fixes 

- src/modules/project/pages/projectCreate/components/FormContinueButton.tsx
- src/modules/project/pages/projectCreate/views/ProjectCreateRewards.tsx
https://linear.app/geyser/issue/GYS-7918/copy-update
> feat: skip instead of continue on rewards when now rewards added

- src/context/filter.tsx
- src/modules/project/pages/projectView/hooks/useProjectGoalForm.tsx
- src/pages/landing/filters/sort/SortBody.tsx
- src/pages/landing/filters/sort/sortSelection.ts
- src/pages/landing/projects/components/FilterTopBar.tsx
- src/pages/landing/projects/index.tsx
- src/pages/landing/projects/views/index.ts
https://linear.app/geyser/issue/GYS-6737/remove-most-funded-this-week-from-the-tag-results
> Remove most funded of the week

- src/components/molecules/projectDisplay/ProjectEntryCard.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/Rewards.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/Story.tsx
https://linear.app/geyser/issue/GYS-8000/standardize-the-edit-button
> feat: standardize edit icon

- src/modules/project/pages/projectView/hooks/useProjectGoalForm.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-7902/add-error-toast-on-goal-modal
> fix: add error toast in case of server error for project goals

- src/pages/otp/VerifyYourEmailContent.tsx
- src/translations/English.json
https://linear.app/geyser/issue/GYS-7916/update-to-otp
> feat: add email to otp modal

- src/modules/project/pages/projectView/views/projectCreatorViews/sections/rewards/components/RewardsTable.tsx
https://linear.app/geyser/issue/GYS-8000/standardize-the-edit-button
> feat: edit icon on manage rewards screen

- src/modules/project/pages/projectView/views/projectMainBody/sections/Goals.tsx
- src/modules/project/pages/projectView/views/projectMainBody/sections/Story.tsx
https://linear.app/geyser/issue/GYS-8000/standardize-the-edit-button
> feat: standardize edit button for creator tools

- src/modules/project/pages/projectView/hooks/useProjectGoalForm.tsx
https://linear.app/geyser/issue/GYS-8067/goal-edit-error
> Hot-Fix: goal amount validation

- src/pages/grants/grantsPage/components/GrantApplicantCard.tsx
https://linear.app/geyser/issue/GYS-8023/make-modal-size-the-same-as-the-payment-flow-modal
> Fix: same size grant modals

- src/pages/entry/creation/editor/EntryCreateEdit.tsx
https://linear.app/geyser/issue/GYS-8036/add-placeholder-text-in-entry
> fix: add placeholder for entry

- src/modules/project/pages/projectCreate/views/ProjectDetails.tsx
https://linear.app/geyser/issue/GYS-8010/update-copy
> Fix: show skip when form untouched

- src/pages/grants/grantsPage/components/GrantApplicantCard.tsx
https://linear.app/geyser/issue/GYS-8042/contributors-display-on-single-line
> Feat: additional contributor avatar

- src/pages/grants/grantsPage/GrantPage.tsx
- src/pages/grants/grantsPage/sections/GrantApply.tsx
https://linear.app/geyser/issue/GYS-8033/grant-application-error
> feat: show pending in the select project apply

- src/pages/grants/components/ContributionsWidget.tsx
- src/pages/grants/grantsPage/sections/GrantSummary.tsx
Reverts geyserfund/geyser-app#1585
> Revert "hotfix: change time for nashville grant to july25"

- src/constants/platform/defaultViewTags.ts
update featured project to miprimerbitcoin
> changeset: update featured project to miprimerbitcoin

- src/pages/grants/grantsPage/GrantPage.tsx
- src/pages/grants/grantsPage/components/GrantApplicantCard.tsx
https://linear.app/geyser/issue/GYS-8431/build-apply-for-community-voting-grants
> Feat: Grant thailand 

- src/modules/discovery/hooks/useActivityHook.ts
- src/modules/discovery/pages/landing/views/defaultView/components/ProjectDisplayBody.tsx
- src/modules/discovery/pages/landing/views/defaultView/components/ProjectRowLayout.tsx
- src/modules/discovery/pages/landing/views/defaultView/sections/WelcomeCard.tsx
- src/modules/discovery/state/lastVisitedAtom.ts
- src/modules/profile/pages/profilePage/views/account/views/AccountInfo.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/views/ProfileContributions.tsx
- src/modules/profile/pages/profilePage/views/profileTabs/views/ProfileFollowed.tsx
- src/modules/project/pages1/projectView/views/body/sections/contributionSummary/components/ProjectBalanceDisplay.tsx
- src/modules/project/pages1/projectView/views/body/sections/header/Header.tsx
- src/modules/project/pages1/projectView/views/body/sections/header/components/LightningAddress.tsx
> fix: final post deployment qa fixes

- src/modules/discovery/pages/myProjects/MyProjects.tsx
- src/modules/discovery/pages/myProjects/components/Contributions.tsx
- src/shared/constants/platform/url.ts
https://linear.app/geyser/issue/GYS-8668/rewards-icon-in-dark-mode
https://linear.app/geyser/issue/GYS-8674/low-quality-image
> fix: images and image urls

- src/config/theme/components/badgeTheme.ts
- src/modules/project/pages1/projectView/views/rewards/RewardView.tsx
> fix: add hidden badge for hidden rewards

- src/modules/project/graphql/fragments/funderFragment.ts
- src/modules/project/graphql/queries/funderQuery.ts
- src/modules/project/pages1/projectView/hooks/useUserContributorToCurrentProject.ts
- src/modules/project/pages1/projectView/views/body/sections/leaderboardSummary/components/Contributions.tsx
- src/modules/project/pages1/projectView/views/body/sections/leaderboardSummary/components/Leaderboard.tsx
- src/modules/project/pages1/projectView/views/leaderboard/views/leaderboard/components/LeaderboardItem.tsx
- src/shared/constants/components/dimensions.ts
- src/types/generated/graphql.ts
> feat: add current user in the project leaderboard

- src/modules/project/graphql/fragments/funderFragment.ts
- src/modules/project/graphql/queries/funderQuery.ts
- src/modules/project/pages1/projectView/hooks/useUserContributorToCurrentProject.ts
- src/types/generated/graphql.ts
> fix: update to fit name changes

- src/context/serviceWorkerUpdate.tsx
> fix: add refetch service worker on load

- src/AppLayout.tsx
- src/api/airtable.ts
- src/modules/notification/InfoBanner.tsx
- src/modules/notification/InfoBannerAtom.ts
> feat: add info banner from airtable data

- package.json
- src/components/molecules/AuthModal.tsx
- src/modules/navigation/platformNavBar/PlatformNavBar.tsx
- src/pages/auth/ConnectWithEmail.tsx
- src/pages/auth/ConnectWithLightning.tsx
- src/pages/auth/ConnectWithNostr.tsx
- src/pages/auth/SocialConfig.tsx
- src/pages/auth/components/NotificationPromptModal.tsx
- src/pages/auth/hooks/useNotificationPromptModal.ts
- src/pages/auth/state/notificationPromptAtom.ts
- src/pages/otp/VerifyYourEmail.tsx
- src/pages/otp/VerifyYourEmailContent.tsx
- src/pages/otp/components/ReceiveOneTimePassword.tsx
- src/pages/otp/components/VerifyOneTimePassword.tsx
- yarn.lock
> feat: add login with email and refactor OTP UI

- src/modules/project/pages1/projectDashboard/views/ProjectDashboardDetails.tsx
> fix: allow online

- src/pages/grants/constants.ts
- src/pages/grants/hooks/useGrant.tsx
> fix: add custom grant url and make thailand grant a voting grant

- src/modules/discovery/pages/leaderboard/components/TopProjects.tsx
- src/modules/project/pages1/projectFunding/views/fundingDetails/sections/FundingDetailsUserComment.tsx
- src/modules/project/pages1/projectView/views/rewards/hooks/useProjectRewardForm.ts
- src/modules/project/pages1/projectView/views/rewards/shared/ProjectRewardForm.tsx
- src/pages/grants/grantsPage/components/GrantApplicantCard.tsx
- src/shared/components/controlledInput/ControlledSwitchInput.tsx
- src/shared/components/controlledInput/ControlledTextInput.tsx
- src/shared/molecules/MediaControlWithReorder.tsx
https://linear.app/geyser/issue/GYS-8818/pre-order
https://linear.app/geyser/issue/GYS-8775/public-message-hover-top-nav-bar-mobile
https://linear.app/geyser/issue/GYS-8780/command-click-on-project-should-open-new-tab-to-project
https://linear.app/geyser/issue/GYS-8777/open-in-new-tab
https://linear.app/geyser/issue/GYS-8829/error-message
> Minor fixes

- src/modules/project/forms/ProjectCreationWalletConnectionForm.tsx
> changeset: add speed wallet to the create/update lightning wallet section

- src/shared/molecules/FileUpload.tsx
> fix: disable multiple file uploads from useDropzone

- src/modules/project/pages1/projectFunding/views/fundingDetails/sections/FundingDetailsPrivateCommentPrompt.tsx
- src/modules/project/pages1/projectView/views/rewards/shared/ProjectRewardForm.tsx
- src/types/generated/graphql.ts
> feat: add a new field for lightning address

- src/modules/discovery/pages/activity/ActivityFeed.tsx
- src/modules/guardians/components/DesktopGuardiansIllustration.tsx
resolves GYS-9182, guardians hover issue
> fix: guardians page hover effect not working

- src/config/routes/routeGroups.ts
- src/modules/project/pages1/projectFunding/layouts/FundingLayout.tsx
- src/modules/project/pages1/projectFunding/layouts/FundingSummaryWrapper.tsx
- src/modules/project/pages1/projectFunding/views/fundingPayment/state/paymentMethodAtom.ts
resolves GYS-9329, GYS-9346, GYS-9307
> hotfix: Sajal/gys-9346-after-clicking-credit-card-i-cant-click-lightningonchain

- src/modules/discovery/pages/landing/views/defaultView/sections/WelcomeCard.tsx
Reverts geyserfund/geyser-app#1766
> Revert "changeset: update copy to test"

- src/modules/discovery/pages/landing/views/defaultView/sections/WelcomeCard.tsx
Reverts geyserfund/geyser-app#1767
> Revert "Revert "changeset: update copy to test""

- src/modules/discovery/pages/landing/views/defaultView/sections/WelcomeCard.tsx
Reverts geyserfund/geyser-app#1769
> Revert "Revert "Revert "changeset: update copy to test"""

- package.json
- src/modules/guardians/data.ts
- src/modules/guardians/pages/character/components/PartnerList.tsx
- src/modules/guardians/pages/main/GuardiansMainPage.tsx
- src/shared/constants/platform/url.ts
> Add guardian partner

- .cursor/rules/contribution.mdc
- src/modules/project/pages1/projectFunding/views/fundingDetails/FundingDetails.tsx
- src/modules/project/pages1/projectFunding/views/fundingInit/FundingInit.tsx
- src/modules/project/pages1/projectFunding/views/fundingPayment/Payment.tsx
- src/shared/hooks/useSpeedWalletParams.tsx
> feat: add payment with speedwallet option

- src/modules/project/Project.tsx
> fix: add heroId of loggedin users to url

- language/translations/en.json
- src/modules/discovery/pages/landing/views/defaultView/components/FeaturedDisplayCard.tsx
- src/modules/discovery/pages/landing/views/defaultView/components/FeaturedGrantCard.tsx
- src/modules/discovery/pages/landing/views/defaultView/components/FeaturedProjectCard.tsx
- src/modules/discovery/pages/landing/views/defaultView/components/MiniProjectCard.tsx
- src/modules/discovery/pages/landing/views/defaultView/sections/Featured.tsx
- src/modules/discovery/pages/landing/views/defaultView/sections/FeaturedProjectsCarousel.tsx
- src/modules/project/Project.tsx
- src/pages/grants/grantsPage/sections/GrantSummary.tsx
resolves GYS-9634
partially resolves GYS-9607
resolves GYS-9633
> feat: featured carousel can feature, projects, grants or displays

- package.json
- src/modules/discovery/pages/landing/views/defaultView/sections/Featured.tsx
- src/modules/guardians/pages/main/components/Partners.tsx
> changeset: update rewardId for featured project and guardians

- src/modules/project/navigation/components/BackButton.tsx
- src/modules/project/navigation/components/ProjectPreLaunchNav.tsx
> fix: add back button in pre launch nav

- src/components/molecules/AuthModal.tsx
- src/config/apollo-client/apolloClient.ts
- src/config/routes/routes.tsx
- src/modules/auth/ConnectWithNostr.tsx
- src/modules/auth/ConnectWithSocial.tsx
- src/modules/auth/hooks/useNostrExtensionLogin.tsx
- src/modules/auth/pages/SignOut.tsx
- src/modules/auth/useAuthToken.tsx
- src/modules/navigation/platformNavBar/PlatformNavBar.tsx
- src/modules/profile/pages/profilePage/views/account/components/ConnectAccounts.tsx
- src/modules/project/pages1/projectCreation/views/ProjectCreateStart.tsx
- src/pages/grants/grantsPage/sections/GrantApply.tsx
- src/shared/constants/config/routerPaths.ts
> fix: update auth flow

- package.json
- src/modules/navigation/platformNavBar/profileNav/components/ModeChange.tsx
- src/modules/project/funding/state/fundingFormAtom.ts
- src/modules/project/pages1/projectFunding/views/fundingInit/sections/GeyserTipInput.tsx
- src/modules/project/pages1/projectView/views/body/sections/contributionSummary/ContributionSummary.tsx
- src/shared/constants/platform/languages.ts
- src/shared/constants/platform/url.ts
> fix: add icons for payment methods

- package.json
- packages/testing/vitest/modules/project/funding/state/fundingFormAtom.mock.ts
- packages/testing/vitest/modules/project/funding/state/fundingFormAtom.test.helpers.ts
- packages/testing/vitest/modules/project/funding/state/fundingFormAtom.test.ts
> test: add tests for shipping costs and update the rest of the tests accordingly
